site_name: Clash.meta Docs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - toc.integrate
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference



# nav:
#   - Home: index.md
#   - example: example.md
#   - Yaml: yaml.md
#   - Used: /used/
#   - Config: /config/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

repo_url:  https://github.com/MetaCubeX/Clash.Meta
repo_name: MetaCubeX/Clash.Meta