site_name: Clash.meta Docs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - toc.integrate
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference



nav:
  - 简介: index.md
  - 支持clash.meta的工具: client.md
  - 配置示例: example.md
  - 配置详解: 
    - grammar.md
    - 配置:
      - general: config/general.md
      - tun: config/tun.md
      - dns:
        - config/dns/dns.md
        - hosts: config/dns/hosts.md
        - 域名嗅探: config/dns/sniffer.md
    - 代理:
      - config/proxies/proxies.md
      - http: config/proxies/http.md
      - socks: config/proxies/socks.md
      - ss: config/proxies/ss.md
      - ssr: config/proxies/ssr.md
      - vmess: config/proxies/vmess.md
      - vless: config/proxies/vless.md
      - trojan: config/proxies/trojan.md
      - hysteria: config/proxies/hysteria.md
      - tuic: config/proxies/tuic.md
      - wg: config/proxies/wg.md
    - 代理策略:
      - config/proxy-groups/proxy-groups.md
      - 内置策略: config/proxy-groups/built-in.md
      - 手动选择: config/proxy-groups/select.md
      - 自动选择: config/proxy-groups/url-test.md
      - 自动回退: config/proxy-groups/fallback.md
      - 负载均衡: config/proxy-groups/load-balance.md
      - 链式代理: config/proxy-groups/relay.md
      - 指定接口以及路由标记: config/proxy-groups/interface-name-and-routing-mark.md
    - 代理集合:
      - config/proxy-providers/proxy-providers.md
      - 代理集合内容: config/proxy-providers/content.md
      - 引用代理集合: config/proxy-providers/use.md
      - 筛选代理集合: config/proxy-providers/filter.md
      - 健康检查: config/proxy-providers/health-check.md
    - 规则:
      - config/rules/rules.md
      - 域名规则: config/rules/domain.md
      - IP规则: config/rules/ipcidr.md
      - 端口规则: config/rules/port.md
      - 进程规则: config/rules/process.md
      - 逻辑规则: config/rules/logic.md
      - GEO规则: config/rules/geox.md
      - 入站类型规则: config/rules/intype.md
      - 规则集合: config/rules/rule-provider.md
      - 子规则: config/rules/sub-rule.md
      - 最终匹配: config/rules/match.md
    - 规则集合: config/rule-providers.md
    - 子规则: config/sub-rules.md
    - 流量入站: config/listeners.md
    - 隧道: config/tunnels.md
    - 实验性: config/test.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

repo_url:  https://github.com/MetaCubeX/Clash.Meta
repo_name: MetaCubeX/Clash.Meta