site_name: Clash.Meta Docs
repo_url:  https://github.com/MetaCubeX/Clash.Meta
repo_name: MetaCubeX/Clash.Meta

theme:
  name: material
  logo: assets/logo.webp
  favicon: assets/logo.webp
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    # - toc.integrate
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


nav:
  - 简介: index.md
  - 支持 Clash.Meta 的工具: client/index.md
  - 配置示例: example/index.md
  - 配置详解: 
    - config/index.md
    - 全局配置: config/general.md
    - Tun配置: config/tun.md
    - DNS配置:
      - config/dns/index.md
      - hosts: config/dns/hosts.md
      - 域名嗅探: config/dns/sniffer.md
      - 解析流程: config/dns/diagram.md
    - 代理配置:
      - config/proxies/index.md
      - HTTP: config/proxies/http.md
      - SOCKS: config/proxies/socks.md
      - Shadowsocks: config/proxies/ss.md
      - ShadowsocksR: config/proxies/ssr.md
      - VMess: config/proxies/vmess.md
      - VLESS: config/proxies/vless.md
      - Trojan: config/proxies/trojan.md
      - Hysteria: config/proxies/hysteria.md
      - TUIC: config/proxies/tuic.md
      - WireGuard: config/proxies/wg.md
    - 策略组配置:
      - config/proxy-groups/index.md
      - 内置策略: config/proxy-groups/built-in.md
      - 手动选择: config/proxy-groups/select.md
      - 自动选择: config/proxy-groups/url-test.md
      - 自动回退: config/proxy-groups/fallback.md
      - 负载均衡: config/proxy-groups/load-balance.md
      - 链式代理: config/proxy-groups/relay.md
      - 指定接口以及路由标记: config/proxy-groups/interface-name-and-routing-mark.md
    - 代理集合配置:
      - config/proxy-providers/index.md
      - 代理集合内容: config/proxy-providers/content.md
      - 引用代理集合: config/proxy-providers/use.md
      - 筛选代理集合: config/proxy-providers/filter.md
      - 健康检查: config/proxy-providers/health-check.md
    - 规则配置:
      - config/rules/index.md
      - 域名规则: config/rules/domain.md
      - IP规则: config/rules/ipcidr.md
      - 端口规则: config/rules/port.md
      - 进程规则: config/rules/process.md
      - 逻辑规则: config/rules/logic.md
      - GEO规则: config/rules/geox.md
      - 入站类型规则: config/rules/intype.md
      - 规则集合: config/rules/rule-provider.md
      - 子规则: config/rules/sub-rule.md
      - 最终匹配: config/rules/match.md
      - 子规则: config/sub-rules.md
    - 流量入站: config/listeners.md
    - 流量隧道: config/tunnels.md
    - 实验性: config/test.md
  - API: api/index.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - toc:
      permalink: true
      toc_depth: 3
      anchorlink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

