site_name: Clash.meta Docs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    # - navigation.tabs
  palette:
    scheme: default
    primary: white
    accent: deep purple


# nav:
#   - Home: index.md
#   - example: example.md
#   - Yaml: yaml.md
#   - Used: /used/
#   - Config: /config/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

repo_url:  https://github.com/MetaCubeX/Clash.Meta
repo_name: MetaCubeX/Clash.Meta